import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <nav className="flex gap-6 p-6 border-b">
          <Link href="/" className="font-medium">Home</Link>
          <a href="/about" className="font-medium">About</a>
          <a href="/blog" className="font-medium">Blog</a>
          <a href="/projects" className="font-medium">Projects</a>
      </nav>

      {children}
      </body>

    </html>
  );
}
