import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="flex gap-4 p-4 bg-mint text-darktext font-medium shadow-md">
          <Link href="/" className="px-4 py-2 rounded-full border-2 border-black bg-white text-black font-semibold hover:bg-[#A3D2CA] hover:border-[#A3D2CA] hover:text-white transition-all duration-200">Home</Link>
          <a href="/blog" className="px-4 py-2 rounded-full border-2 border-black bg-white text-black font-semibold hover:bg-[#A3D2CA] hover:border-[#A3D2CA] hover:text-white transition-all duration-200">Blog</a>
          <a href="/projects" className="px-4 py-2 rounded-full border-2 border-black bg-white text-black font-semibold hover:bg-[#A3D2CA] hover:border-[#A3D2CA] hover:text-white transition-all duration-200">Projects</a>
          <a href="/fun" className="px-4 py-2 rounded-full border-2 border-black bg-white text-black font-semibold hover:bg-[#A3D2CA] hover:border-[#A3D2CA] hover:text-white transition-all duration-200">Fun</a>
      </nav>
      {children}
      </body>

    </html>
  );
}
